# Generated by Django 4.2.7 on 2025-11-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'активен'), ('closed', 'закрыт')], db_index=True, default='active', max_length=20),
        ),
    ]
